apiVersion: apps/v1
kind: Deployment
metadata:
  name: ds-pardot-filter-prod
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-pardot-filter-prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ds-pardot-filter-prod
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pardot-filter-prod
        - secretRef:
            name: pardot-filter-prod
        image: registry.gitlab.com/cads-platform-ds-projects/pardot-filter:latest
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 8055
          name: http
        resources:
          limits:
            cpu: 750m
            memory: 500M
          requests:
            cpu: 150m
            memory: 300M
      imagePullSecrets:
      - name: regcred-ds-projs