apiVersion: v1
kind: Service
metadata:
  labels:
    app: ds-pardot-filter-prod
  name: ds-pardot-filter-prod
  namespace: production
spec:
  ports:
  - name: http
    port: 8055
    protocol: TCP
    targetPort: 8055
  selector:
    app: ds-pardot-filter-prod
  type: ClusterIP
